server:
  servlet:
    context-path: /fast-api
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt
  servlet:
    multipart:
      location: /opt/upload/tmp
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:h2:file:~/.fc/db/connect
          driver-class-name: org.h2.Driver
          username: admin
          password: 123456
#MyBatis
mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  mapper-locations: classpath*:/mapper/**/*.xml
  #  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-super-type: com.dandandog.framework.core.entity.BaseEntity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型 ;
      id-type: assign_uuid
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      insert-strategy: not_null
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      #驼峰下划线转换
      table-underline: false
    banner: false
  #原生配置
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
    local-cache-scope: SESSION
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


logging:
  config: classpath:config/logback.xml
  file:
    name: logs/${spring.application.name}.log
