spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:h2:file:~/.fc/db/connect
          driver-class-name: org.h2.Driver
          username: admin
          password: 123456
