server:
  servlet:
    context-path: /fast-api
  port: 8080
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt
  servlet:
    multipart:
      location: /opt/upload/tmp
      max-file-size: 10MB
      max-request-size: 100MB
  druid:
    stat-view-servlet:
      enabled: true
 #     loginUsername: admin
 #     loginPassword: 123456
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

logging:
  config: classpath:config/logback.xml
  file:
    name: logs/${spring.application.name}.log
