server:
  servlet:
    context-path: /fast-api
  port: 8080
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt
  servlet:
    multipart:
      location: /opt/upload/tmp
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:h2:file:~/.fc/db/connect
          driver-class-name: org.h2.Driver
          username: admin
          password: 123456

logging:
  config: classpath:config/logback.xml
  file:
    name: logs/${spring.application.name}.log
